import Head from 'next/head';
import Home from './home';

export default function App() {
  return (
    <>
      <Head>
        <title>The Quran App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <meta http-equiv='Content-Type' content='text/html' charset='utf-8' />
        <link rel='icon' href='https://i.postimg.cc/zG0HVyzY/profile-pic.png' />
      </Head>
      <Home />
    </>
  );
}
